### PR TITLE
Fix for building with modern GCC and copies the correct crt0.o for the packages.

### PR DESCRIPTION
**Pull request by MrNetrix**

### CODE REVIEW

**Comment by xyzz** [comment]
Is there really a need to manually copy crt0.o? This should've been fixed with this commit: https://github.com/xyzz/vita-newlib/commit/37639ed81a0400283c9e173d933d6f8529e71c07

What's the reason for `--disable-werror`?

**Comment by MrNetrix** [comment]
crt0.o put into the packages has always been the wrong one, even with that
commit.

--disable-werror is so warnings aren't treated as errors. binutils for
MinGW fails to build on modern versions of GCC because they are pickier
about what gives warnings. You'll see that --disable-werror is used to
build binutils for Linux, so it doesn't make sense that it's not using it
for MinGW as well anyway.

**Comment by xyzz** [comment]
I just checked by rebuilding the toolchain and it's definitely the correct crt0.o.

```
build@build-desktop:~/toolchain/gcc-arm-none-eabi-4_9-2015q2-20150609$ readelf -a install-native/arm-vita-eabi/lib/crt0.o
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              REL (Relocatable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          0 (bytes into file)
  Start of section headers:          436 (bytes into file)
  Flags:                             0x5000000, Version5 EABI
  Size of this header:               52 (bytes)
  Size of program headers:           0 (bytes)
  Number of program headers:         0
  Size of section headers:           40 (bytes)
  Number of section headers:         15
  Section header string table index: 12

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .text             PROGBITS        00000000 000034 000000 00  AX  0   0  2
  [ 2] .data             PROGBITS        00000000 000034 000000 00  WA  0   0  1
  [ 3] .bss              NOBITS          00000000 000034 000000 00  WA  0   0  1
  [ 4] .text._init_vita_ PROGBITS        00000000 000034 000030 00  AX  0   0  4
  [ 5] .rel.text._init_v REL             00000000 000634 000040 08     13   4  4
  [ 6] .text._start      PROGBITS        00000000 000064 000028 00  AX  0   0  4
  [ 7] .rel.text._start  REL             00000000 000674 000028 08     13   6  4
  [ 8] .rodata.str1.4    PROGBITS        00000000 00008c 00001d 01 AMS  0   0  4
  [ 9] .debug_frame      PROGBITS        00000000 0000ac 000048 00      0   0  4
  [10] .rel.debug_frame  REL             00000000 00069c 000020 08     13   9  4
  [11] .ARM.attributes   ARM_ATTRIBUTES  00000000 0000f4 000035 00      0   0  1
  [12] .shstrtab         STRTAB          00000000 000129 000089 00      0   0  1
  [13] .symtab           SYMTAB          00000000 00040c 000190 10     14  16  4
  [14] .strtab           STRTAB          00000000 00059c 000096 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings)
  I (info), L (link order), G (group), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)

There are no section groups in this file.

There are no program headers in this file.

Relocation section '.rel.text._init_vita_newlib' at offset 0x634 contains 8 entries:
 Offset     Info    Type            Sym.Value  Sym. Name
00000004  0000110a R_ARM_THM_CALL    00000000   _init_vita_heap
00000008  0000120a R_ARM_THM_CALL    00000000   _init_vita_reent
0000000c  0000130a R_ARM_THM_CALL    00000000   _init_vita_malloc
00000012  0000142f R_ARM_THM_MOVW_AB 00000000   _newlib_fd_mutex
00000016  0000072f R_ARM_THM_MOVW_AB 00000000   .LC0
0000001e  00000730 R_ARM_THM_MOVT_AB 00000000   .LC0
00000022  00001430 R_ARM_THM_MOVT_AB 00000000   _newlib_fd_mutex
00000026  0000150a R_ARM_THM_CALL    00000000   sceKernelCreateLwMutex

Relocation section '.rel.text._start' at offset 0x674 contains 5 entries:
 Offset     Info    Type            Sym.Value  Sym. Name
00000004  0000100a R_ARM_THM_CALL    00000001   _init_vita_newlib
00000008  00000a2f R_ARM_THM_MOVW_AB 0000001c   .LC1
0000000e  00000a30 R_ARM_THM_MOVT_AB 0000001c   .LC1
0000001a  0000170a R_ARM_THM_CALL    00000000   main
0000001e  0000180a R_ARM_THM_CALL    00000000   exit

Relocation section '.rel.debug_frame' at offset 0x69c contains 4 entries:
 Offset     Info    Type            Sym.Value  Sym. Name
00000014  00000e02 R_ARM_ABS32       00000000   .debug_frame
00000018  00000502 R_ARM_ABS32       00000000   .text._init_vita_newli
00000030  00000e02 R_ARM_ABS32       00000000   .debug_frame
00000034  00000802 R_ARM_ABS32       00000000   .text._start

There are no unwind sections in this file.

Symbol table '.symtab' contains 25 entries:
   Num:    Value  Size Type    Bind   Vis      Ndx Name
     0: 00000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 00000000     0 FILE    LOCAL  DEFAULT  ABS crt0.c
     2: 00000000     0 SECTION LOCAL  DEFAULT    1 
     3: 00000000     0 SECTION LOCAL  DEFAULT    2 
     4: 00000000     0 SECTION LOCAL  DEFAULT    3 
     5: 00000000     0 SECTION LOCAL  DEFAULT    4 
     6: 00000000     0 NOTYPE  LOCAL  DEFAULT    4 $t
     7: 00000000     0 NOTYPE  LOCAL  DEFAULT    8 .LC0
     8: 00000000     0 SECTION LOCAL  DEFAULT    6 
     9: 00000000     0 NOTYPE  LOCAL  DEFAULT    6 $t
    10: 0000001c     0 NOTYPE  LOCAL  DEFAULT    8 .LC1
    11: 00000000     0 SECTION LOCAL  DEFAULT    8 
    12: 00000000     0 NOTYPE  LOCAL  DEFAULT    8 $d
    13: 00000010     0 NOTYPE  LOCAL  DEFAULT    9 $d
    14: 00000000     0 SECTION LOCAL  DEFAULT    9 
    15: 00000000     0 SECTION LOCAL  DEFAULT   11 
    16: 00000001    48 FUNC    GLOBAL DEFAULT    4 _init_vita_newlib
    17: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND _init_vita_heap
    18: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND _init_vita_reent
    19: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND _init_vita_malloc
    20: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND _newlib_fd_mutex
    21: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND sceKernelCreateLwMutex
    22: 00000001    40 FUNC    GLOBAL DEFAULT    6 _start
    23: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND main
    24: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND exit

No version information found in this file.
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_VFP_arch: VFPv3
  Tag_NEON_arch: NEONv1
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align8_needed: Yes
  Tag_ABI_align8_preserved: Yes, except leaf SP
  Tag_ABI_enum_size: small
  Tag_ABI_VFP_args: VFP registers
  Tag_ABI_optimization_goals: Aggressive Speed
  Tag_unknown_34: 1 (0x1)
```

**Comment by MrNetrix** [comment]
It's working now. Looks like there were old files. I reverted the manually copying.

**Pull request merged**
